name: condsig_env
channels:
  - bioconda
  - conda-forge

dependencies:
    - python=3.7
    - bedtools=2.30.0
    - setuptools
    - pip
    - ipython
    - pandas>=1.3.5
    - numpy>=1.21.2
    - scipy>=1.6.2
    - pybigwig>=0.3.17
    - shap>=0.39.0
    - xgboost>=1.5.0
    - matplotlib>=3.4.2